version: "3"
services:
  rtc:
    image: DOCKER_REGISTRY_RTC_REPO
    env_file:
    - .env
    environment:
      - MQ_HOST=localhost
      - MQ_USER=${MQ_USERNAME}
      - MQ_PASSWORD=${MQ_PASSWORD}
      - RTC_IP_ADDRESS=${RTC_IP_ADDRESS}
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: curl --fail http://localhost:8010/liveness || exit 1
      interval: 10s
      timeout: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
      haproxy:
        condition: service_started

  rabbitmq:
    env_file:
    - .env
    build: RabbitMQ/.
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
        - rabbitdata:/var/lib/rabbitmq/
        - rabbitlog:/var/log/rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: "rabbitmqctl status | grep 'port: 5672' || exit 1"
      interval: 5s
      timeout: 30s

  haproxy:
    build: HAProxy/.
    network_mode: host
    volumes:
      - ./HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    command: --rolling-restart --cleanup --label-enable --debug --schedule "0 0 */1 * * *"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/datasource_prometheus.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./Grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/all.yaml
      - ./Grafana/custom.ini:/etc/grafana/custom.ini
      - ./Grafana/RTC-dashboard.json:/var/lib/grafana/dashboards/RTC-dashboard.json
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini

  prometheus:
    image: 'prom/prometheus'
    volumes:
      - ./Prometheus/scrape_configs.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    healthcheck:
      test: "prometheus --version"
      interval: 5s
      timeout: 5s

  haproxy-exporter:
    image: 'quay.io/prometheus/haproxy-exporter:latest'
    command:
      - '--haproxy.scrape-uri=http://haproxy:8404/stats;csv'
    ports:
      - '9101:9101'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  prom_data:
  rabbitdata:
  rabbitlog:
