{
 "title": "RTC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total active intercoms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rtc_active_intercoms_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Intercoms ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rtc_active_intercoms_total", "legendFormat": "Active Intercoms " }
   ]
  },
  {
   "title": "Intercoms lifetime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quantile(0.01, rtc_active_intercoms_total)",
     "legendFormat": "p01"
    },
    {
     "expr": "quantile(0.01, rtc_intercom_work_duration_seconds)",
     "legendFormat": "p1"
    },
    {
     "expr": "quantile(0.05, rtc_intercom_work_duration_seconds)",
     "legendFormat": "p5"
    },
    {
     "expr": "quantile(0.1, rtc_intercom_work_duration_seconds)",
     "legendFormat": "p10"
    },
    {
     "expr": "quantile(0.2, rtc_intercom_work_duration_seconds)",
     "legendFormat": "p20"
    },
    {
     "expr": "quantile(0.5, rtc_intercom_work_duration_seconds)",
     "legendFormat": "p50"
    },
    {}
   ]
  },
  {
   "title": "Active calls ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rtc_active_calls_total", "legendFormat": "Active calls" }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rtc_rmq_fatal_errors{}", "legendFormat": "rmq errors" },
    { "expr": "rtc_rmq_msgs_consumed{}", "legendFormat": "rmq msgs consumed" },
    { "expr": "rtc_rmq_msgs_published{}", "legendFormat": "rmq msgs published" }
   ]
  },
  {
   "title": "Sputnik services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_backend_up{backend=~\".*end\"}",
     "legendFormat": "{{ backend }}"
    },
    {}
   ]
  },
  {
   "title": "response time average in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_http_response_time_average_seconds{}",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "response with error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_response_errors_total[$__rate_interval])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total[$__rate_interval])",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "The average network traffic received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}