global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: rtc
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['rtc:8080']

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: hapoxy
    static_configs:
      - targets: ['haproxy-exporter:9101']
